//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TesteEntity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class testdevEntities : DbContext
    {
        public testdevEntities()
            : base("name=testdevEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<produto> produto { get; set; }
        public virtual DbSet<produto_grupo> produto_grupo { get; set; }
        public virtual DbSet<usuario> usuario { get; set; }
        public virtual DbSet<venda> venda { get; set; }
        public virtual DbSet<venda_produto> venda_produto { get; set; }
    }
}
