//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TesteEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuario
    {
        public long cod { get; set; }
        public string login { get; set; }
        public string senha { get; set; }
    }
}
