//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TesteEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class venda_produto
    {
        public long cod { get; set; }
        public long codVenda { get; set; }
        public long codProduto { get; set; }
        public decimal precoVenda { get; set; }
        public decimal quantidade { get; set; }
    
        public virtual produto produto { get; set; }
        public virtual venda venda { get; set; }
    }
}
